return {
    {
        "nvim-treesitter/nvim-treesitter",
        main = "nvim-treesitter.configs",
        build = ":TSUpdate",
        event = { "BufReadPost", "BufNewFile" },
        opts = {
            ensure_installed = {
                "bash",
                "html",
                "css",
                "gitignore",
                "c",
                "lua",
                "go",
                "gomod",
                "gosum",
                "dockerfile",
                "dart",
                "graphql",
                "http",
                "java",
                "php",
                "rust",
                "scss",
                "markdown",
                "markdown_inline",
                "python",
                "sql",
                "svelte",
                "query",
                "regex",
                "tsx",
                "javascript",
                "typescript",
                "yaml",
                "json",
                "jsonc",
                "angular",
            },
            highlight = { enable = true },
            indent = { enable = true },
            autotag = { enable = true }, -- HTML autotags
            auto_install = true,         -- installs missing parsers when open a buffer
        },
    },
}
